// DIAL theme tokens — three visual directions exposed as CSS variables.
// Components read tokens from var(--dial-*); a theme object also exposes a
// `name` so a couple of structural choices (header style, code blocks) can
// branch on theme without piling on extra CSS variables.

const DIAL_THEMES = {
  cream: {
    name: 'cream',
    label: 'A · Pairpoint Cream',
    sublabel: 'Consumer-friendly · light · Vodafone red as accent',
    vars: {
      '--dial-bg':        '#f5f3ec',
      '--dial-bg-soft':   '#ebe7da',
      '--dial-surface':   '#ffffff',
      '--dial-surface-2': '#faf8f1',
      '--dial-border':    '#d8d4ca',
      '--dial-border-2':  '#e8e4d8',
      '--dial-text':      '#1a1a1a',
      '--dial-text-2':    '#4a4a4a',
      '--dial-muted':     '#7a7568',
      '--dial-accent':    '#e60000',
      '--dial-accent-2':  '#b80000',
      '--dial-accent-bg': 'rgba(230,0,0,0.08)',
      '--dial-ok':        '#1f8a5b',
      '--dial-warn':      '#b86a00',
      '--dial-radius':    '10px',
      '--dial-radius-sm': '6px',
      '--dial-radius-lg': '16px',
      '--dial-border-w':  '1px',
      '--dial-shadow':    '0 1px 0 rgba(0,0,0,0.04), 0 8px 24px rgba(20,12,0,0.04)',
      '--dial-shadow-lg': '0 12px 40px rgba(20,12,0,0.10)',
      '--dial-font':      '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif',
      '--dial-font-mono': '"JetBrains Mono", "SF Mono", ui-monospace, Consolas, monospace',
      '--dial-font-display': '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif',
      '--dial-display-weight': '700',
      '--dial-letter-display': '-0.02em',
      '--dial-letter-tag':     '0.06em',
    },
  },

  dark: {
    name: 'dark',
    label: 'B · Vodafone Dark Pro',
    sublabel: 'Technical · dark · Vodafone red as primary',
    vars: {
      '--dial-bg':        '#0b0d10',
      '--dial-bg-soft':   '#14171c',
      '--dial-surface':   '#181c22',
      '--dial-surface-2': '#1f242c',
      '--dial-border':    '#262b33',
      '--dial-border-2':  '#353c47',
      '--dial-text':      '#e7e9ec',
      '--dial-text-2':    '#c6cad1',
      '--dial-muted':     '#8a93a0',
      '--dial-accent':    '#e60000',
      '--dial-accent-2':  '#ff4d4d',
      '--dial-accent-bg': 'rgba(230,0,0,0.12)',
      '--dial-ok':        '#3ddc97',
      '--dial-warn':      '#ffb454',
      '--dial-radius':    '6px',
      '--dial-radius-sm': '4px',
      '--dial-radius-lg': '10px',
      '--dial-border-w':  '1px',
      '--dial-shadow':    '0 1px 0 rgba(255,255,255,0.02)',
      '--dial-shadow-lg': '0 20px 60px rgba(0,0,0,0.55)',
      '--dial-font':      '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif',
      '--dial-font-mono': '"JetBrains Mono", "SF Mono", ui-monospace, Consolas, monospace',
      '--dial-font-display': '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif',
      '--dial-display-weight': '800',
      '--dial-letter-display': '-0.025em',
      '--dial-letter-tag':     '0.12em',
    },
  },

  mono: {
    name: 'mono',
    label: 'C · Editorial Mono',
    sublabel: 'Brutalist namespace registry · all-mono · 1 red accent',
    vars: {
      '--dial-bg':        '#fafaf7',
      '--dial-bg-soft':   '#f1f0ea',
      '--dial-surface':   '#ffffff',
      '--dial-surface-2': '#f6f5ef',
      '--dial-border':    '#111111',
      '--dial-border-2':  '#111111',
      '--dial-text':      '#0a0a0a',
      '--dial-text-2':    '#1a1a1a',
      '--dial-muted':     '#666666',
      '--dial-accent':    '#e60000',
      '--dial-accent-2':  '#b80000',
      '--dial-accent-bg': 'rgba(230,0,0,0.10)',
      '--dial-ok':        '#0a6b3a',
      '--dial-warn':      '#a85a00',
      '--dial-radius':    '0px',
      '--dial-radius-sm': '0px',
      '--dial-radius-lg': '0px',
      '--dial-border-w':  '1.5px',
      '--dial-shadow':    'none',
      '--dial-shadow-lg': '6px 6px 0 #111111',
      '--dial-font':      '"JetBrains Mono", "SF Mono", ui-monospace, Consolas, monospace',
      '--dial-font-mono': '"JetBrains Mono", "SF Mono", ui-monospace, Consolas, monospace',
      '--dial-font-display': '"JetBrains Mono", "SF Mono", ui-monospace, Consolas, monospace',
      '--dial-display-weight': '700',
      '--dial-letter-display': '-0.04em',
      '--dial-letter-tag':     '0.10em',
    },
  },
};

window.DIAL_THEMES = DIAL_THEMES;
